[oobe]
command = /usr/lib/agentfem/oobe.sh
defaultUid = 1000
defaultName = AgentFEM

[shortcut]
enabled = true

[windowsterminal]
enabled = true
ProfileTemplate = /usr/lib/agentfem/terminal-profile.json

