"""Constitutive laws and material-model helpers."""

from . import catalog
from . import creep
from . import elasticity
from . import fatigue
from . import finite_strain_plasticity
from . import hyperelasticity
from . import material_driver
from . import plasticity
from . import quadrature
from . import user_material
from . import viscoelasticity
from .catalog import ConstitutiveCapability, capabilities, capability
from .creep import (
    ArrheniusPowerLawCreep,
    CreepDamageState,
    CreepDamageUpdate,
    CreepHistory,
    ImplicitCreepBatchUpdate,
    ImplicitCreepState,
    ImplicitCreepUpdate,
    IsotropicPowerLawCreepMaterial,
    KachanovRabotnovCreep,
    ModifiedThetaProjection,
    PowerLawCreep,
    SinhCreep,
    integrate_stress_history,
    isotropic_power_law,
    isotropic_arrhenius_power_law,
)
from .elasticity import (
    AnisotropicElasticMaterial2D,
    ElasticAnisotropic2DProperties,
    ElasticIsotropicProperties,
    ThermoElasticIsotropicProperties,
    TemperatureDependentThermoElasticProperties,
    IsotropicElasticMaterial,
    anisotropic_stress_2d,
    anisotropic_elastic_2d,
    estimate_elastic_wave_speeds,
    isotropic_stress,
    isotropic_elastic,
    thermal_expansion_stress,
    thermal_strain,
    thermoelastic,
    temperature_dependent_thermoelastic,
    thermoelastic_stress,
    orthotropic_plane_stress_2d,
    stress,
)
from .fatigue import (
    BasquinCurve,
    FatigueAssessment,
    FatigueBlock,
    StressCycle,
    TabulatedSNCurve,
    assess_history,
    assess_result_history,
    damage_from_history,
    goodman_amplitude,
    life_scale_factor,
    miner_damage,
    rainflow_cycles,
    turning_points,
)
from .finite_strain_plasticity import (
    FiniteStrainJ2Logarithmic,
    finite_strain_j2_logarithmic,
)
from .hyperelasticity import (
    FiniteStrainKinematics,
    MixedNeoHookeanProperties,
    MooneyRivlinProperties,
    NeoHookeanProperties,
    PlaneStressNeoHookeanProperties,
    kinematics,
    mooney_rivlin,
    mooney_rivlin_plane_stress,
    mixed_condensed_energy_value,
    mixed_neo_hookean,
    neo_hookean,
    neo_hookean_plane_stress,
    plane_stress_first_piola_value,
    plane_stress_out_of_plane_first_piola_from_gradient,
    plane_stress_thickness_stretch_value,
    plane_stress_uniaxial_deformation_gradient,
    supports_hyperelastic_study,
)
from .material_driver import (
    MaterialPointBatchResult,
    MaterialQuadratureResponse,
    update_material_points,
)
from .plasticity import (
    ChabocheCombinedHardening,
    ChabocheState,
    J2LinearIsotropicHardening,
    J2PlasticState,
    J2Update,
    UniaxialPlasticState,
    chaboche,
    update_uniaxial,
    von_mises,
)
from .quadrature import (
    ChabocheQuadratureState,
    CreepQuadratureState,
    J2QuadratureState,
    MaterialQuadratureState,
    QuadratureField,
    QuadratureMaterialMap,
    QuadratureTransaction,
    j2_quadrature_state,
    load_portable_quadrature_state,
    save_portable_quadrature_state,
)
from .user_material import (
    AbaqusUserMaterialBridge,
    MaterialPointInput,
    MaterialPointOutput,
    MaterialStateSchema,
    MaterialStateVariable,
    MaterialTangentCheck,
    MaterialTangentConvention,
    UserMaterial,
    check_material_tangent,
    validated_material_update,
)
from .viscoelasticity import (
    ArrheniusShift,
    GeneralizedMaxwell,
    MaxwellState,
    PronyFit,
    ViscoelasticUpdate,
    WLFShift,
    fit_relaxation_prony,
    standard_linear_solid,
)

__all__ = [
    "catalog",
    "creep",
    "elasticity",
    "fatigue",
    "finite_strain_plasticity",
    "hyperelasticity",
    "material_driver",
    "plasticity",
    "quadrature",
    "user_material",
    "viscoelasticity",
    "AbaqusUserMaterialBridge",
    "ArrheniusPowerLawCreep",
    "ArrheniusShift",
    "AnisotropicElasticMaterial2D",
    "ConstitutiveCapability",
    "BasquinCurve",
    "CreepHistory",
    "ChabocheCombinedHardening",
    "ChabocheQuadratureState",
    "ChabocheState",
    "ImplicitCreepBatchUpdate",
    "CreepQuadratureState",
    "QuadratureMaterialMap",
    "ImplicitCreepState",
    "ImplicitCreepUpdate",
    "IsotropicPowerLawCreepMaterial",
    "CreepDamageState",
    "CreepDamageUpdate",
    "ElasticAnisotropic2DProperties",
    "ElasticIsotropicProperties",
    "ThermoElasticIsotropicProperties",
    "TemperatureDependentThermoElasticProperties",
    "FatigueAssessment",
    "FatigueBlock",
    "StressCycle",
    "IsotropicElasticMaterial",
    "J2LinearIsotropicHardening",
    "J2PlasticState",
    "J2Update",
    "J2QuadratureState",
    "FiniteStrainKinematics",
    "FiniteStrainJ2Logarithmic",
    "MixedNeoHookeanProperties",
    "MooneyRivlinProperties",
    "NeoHookeanProperties",
    "PlaneStressNeoHookeanProperties",
    "MaterialPointInput",
    "MaterialPointBatchResult",
    "MaterialPointOutput",
    "MaterialQuadratureState",
    "MaterialQuadratureResponse",
    "MaterialStateSchema",
    "MaterialStateVariable",
    "MaterialTangentCheck",
    "MaterialTangentConvention",
    "MaxwellState",
    "KachanovRabotnovCreep",
    "ModifiedThetaProjection",
    "PowerLawCreep",
    "PronyFit",
    "QuadratureField",
    "QuadratureTransaction",
    "chaboche",
    "j2_quadrature_state",
    "load_portable_quadrature_state",
    "save_portable_quadrature_state",
    "TabulatedSNCurve",
    "SinhCreep",
    "GeneralizedMaxwell",
    "UniaxialPlasticState",
    "UserMaterial",
    "ViscoelasticUpdate",
    "WLFShift",
    "validated_material_update",
    "update_material_points",
    "check_material_tangent",
    "anisotropic_stress_2d",
    "anisotropic_elastic_2d",
    "assess_history",
    "assess_result_history",
    "estimate_elastic_wave_speeds",
    "capabilities",
    "capability",
    "isotropic_stress",
    "isotropic_elastic",
    "thermal_expansion_stress",
    "thermal_strain",
    "thermoelastic",
    "temperature_dependent_thermoelastic",
    "thermoelastic_stress",
    "integrate_stress_history",
    "isotropic_power_law",
    "isotropic_arrhenius_power_law",
    "life_scale_factor",
    "damage_from_history",
    "goodman_amplitude",
    "finite_strain_j2_logarithmic",
    "fit_relaxation_prony",
    "miner_damage",
    "rainflow_cycles",
    "neo_hookean",
    "neo_hookean_plane_stress",
    "plane_stress_first_piola_value",
    "plane_stress_out_of_plane_first_piola_from_gradient",
    "plane_stress_thickness_stretch_value",
    "plane_stress_uniaxial_deformation_gradient",
    "supports_hyperelastic_study",
    "mixed_neo_hookean",
    "mixed_condensed_energy_value",
    "kinematics",
    "mooney_rivlin",
    "mooney_rivlin_plane_stress",
    "orthotropic_plane_stress_2d",
    "stress",
    "standard_linear_solid",
    "turning_points",
    "update_uniaxial",
    "von_mises",
]
