# SPDX-FileCopyrightText: 2026 Haoming Luo and AgentFEM contributors
# SPDX-License-Identifier: Apache-2.0

"""Engineering-level finite-element operators.

This package gives users K/M/C/F language while keeping weak forms available in
``agentfem.forms`` and low-level assembly in ``agentfem.assembly``.
"""

from . import elasticity
from .core import (
    LumpedMassOperator,
    NonlinearOperatorContribution,
    OperatorForm,
    action,
    assemble_matrix,
    assemble_vector,
    bilinear_form,
    body_force_vector,
    boundary_load_vector,
    boundary_force_vector,
    boundary_model_vector,
    capacity_operator,
    combine,
    compile_form,
    conduction_operator,
    damping_operator,
    dual_product,
    diffusion_operator,
    force_vector,
    form_arity,
    from_ufl,
    flux_vector,
    heat_capacity_operator,
    heat_capacity_vector,
    heat_conduction_operator,
    heat_source_vector,
    inertial_force_vector,
    load_vector,
    lumped_mass,
    lumped_operator,
    mass_action_vector,
    mass_operator,
    linearize,
    residual_operator,
    rayleigh_damping,
    robin_operator,
    robin_source_vector,
    scale,
    source_vector,
    quadratic_form,
    xtmx,
    xtmy,
)
from .dispatch import stiffness
from .cell_gradient import CellGradientEnergyOperator, cell_gradient_energy
from .cell_transfer import (
    CellAverageGradientOperator,
    ConvectedCellFiberIncrement,
    ConvectedCellFiberKinematics,
    ConvectedCellFiberOperator,
    cell_average_gradient,
    convected_cell_fiber,
)
from .displacement_fiber_bending import (
    DisplacementFiberBendingOperator,
    displacement_fiber_bending,
)
from .fiber_bending import (
    FiberDirectionBendingIncrement,
    FiberDirectionBendingOperator,
    FiberDirectionBendingResponse,
    fiber_direction_bending,
)
from .elasticity import (
    elastic_stiffness,
    internal_force_vector,
    stiffness_operator,
    thermal_expansion_vector,
    eigenstrain_vector,
)
from .flow import (
    convective_momentum_operator,
    incompressibility_operator,
    pressure_coupling_operator,
    viscous_flow_operator,
)
from .fourth_order import auxiliary_laplacian_boundary, split_laplacian_operator
from .harmonic import DirectHarmonicSystem, direct_harmonic_system
from .system import (
    FirstOrderSystem,
    LinearSystem,
    SecondOrderSystem,
    first_order_system,
    linear_system,
    second_order_system,
)
from .transport import (
    advection_operator,
    as_velocity,
    burgers_convection_operator,
    intrinsic_time_scale,
    reaction_expression,
    streamline_upwind_operator,
    transient_transport_forms,
)

assemble_lumped_mass = lumped_mass
assemble_lumped_operator = lumped_operator

__all__ = [
    "LumpedMassOperator",
    "CellGradientEnergyOperator",
    "CellAverageGradientOperator",
    "ConvectedCellFiberIncrement",
    "ConvectedCellFiberKinematics",
    "ConvectedCellFiberOperator",
    "FiberDirectionBendingOperator",
    "FiberDirectionBendingResponse",
    "LinearSystem",
    "FirstOrderSystem",
    "OperatorForm",
    "SecondOrderSystem",
    "DirectHarmonicSystem",
    "action",
    "advection_operator",
    "auxiliary_laplacian_boundary",
    "as_velocity",
    "burgers_convection_operator",
    "assemble_lumped_mass",
    "assemble_lumped_operator",
    "assemble_matrix",
    "assemble_vector",
    "bilinear_form",
    "body_force_vector",
    "boundary_load_vector",
    "boundary_force_vector",
    "boundary_model_vector",
    "capacity_operator",
    "cell_gradient_energy",
    "cell_average_gradient",
    "convected_cell_fiber",
    "DisplacementFiberBendingOperator",
    "displacement_fiber_bending",
    "combine",
    "compile_form",
    "conduction_operator",
    "convective_momentum_operator",
    "damping_operator",
    "dual_product",
    "diffusion_operator",
    "direct_harmonic_system",
    "elastic_stiffness",
    "elasticity",
    "force_vector",
    "fiber_direction_bending",
    "FiberDirectionBendingIncrement",
    "form_arity",
    "from_ufl",
    "flux_vector",
    "heat_capacity_operator",
    "heat_capacity_vector",
    "heat_conduction_operator",
    "heat_source_vector",
    "inertial_force_vector",
    "internal_force_vector",
    "incompressibility_operator",
    "intrinsic_time_scale",
    "linear_system",
    "first_order_system",
    "second_order_system",
    "linearize",
    "load_vector",
    "lumped_mass",
    "lumped_operator",
    "mass_action_vector",
    "mass_operator",
    "NonlinearOperatorContribution",
    "pressure_coupling_operator",
    "residual_operator",
    "rayleigh_damping",
    "reaction_expression",
    "robin_operator",
    "robin_source_vector",
    "scale",
    "source_vector",
    "stiffness",
    "stiffness_operator",
    "streamline_upwind_operator",
    "transient_transport_forms",
    "split_laplacian_operator",
    "thermal_expansion_vector",
    "eigenstrain_vector",
    "viscous_flow_operator",
    "quadratic_form",
    "xtmx",
    "xtmy",
]
